name: api-testing Demo
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
      shell: bash
      run: |
        ls -al
    - name: run-test
      shell: bash
      run: |
        ls -al
